{{- if .Values.addons.argocd.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argocd
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
spec:
  targetNamespace: argocd
  chart:
    spec:
      chart: {{ .Values.addons.argocd.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: argocd
        namespace: {{ .Release.Namespace }}

  {{- with .Values.flux }}
  interval: {{ .interval }}
  test:
    enable: false
  install:
    remediation:
      retries: {{ .install.retries }}
  upgrade:
    remediation:
      retries: {{ .upgrade.retries }}
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: {{ .rollback.timeout }}
    cleanupOnFail: {{ .rollback.cleanupOnFail }}
  {{- end }}
  valuesFrom:
    - name: values
      kind: Secret
      valuesKey: "argocd.yaml"
  values:
    hostname: {{ .Values.hostname }}
    createNamespace: false
    global:
      imagePullSecrets:
      - name: private-registry
    controller:
      imagePullSecrets:
      - name: private-registry
    dex:
      imagePullSecrets:
      - name: private-registry
    redis:
      imagePullSecrets:
      - name: private-registry
    {{- if .Values.addons.argocd.sso.enabled }}
    sso:
      enabled: {{ .Values.addons.argocd.sso.enabled }}
      rbac:
        policy.csv: {{- toYaml .Values.addons.argocd.sso.groups | nindent 8 }}
      keycloakClientSecret: {{ .Values.addons.argocd.sso.client_secret }}
      config:
        oidc.config: |
          name: {{ .Values.addons.argocd.sso.provider_name }}
          issuer: https://{{ .Values.sso.oidc.host }}/auth/realms/{{ .Values.sso.oidc.realm }}
          clientID: {{ .Values.addons.argocd.sso.client_id }}
          clientSecret: $oidc.keycloak.clientSecret
          requestedScopes: ["openid","ArgoCD"]
    {{- end }}
    istio:
      enabled: {{ if .Values.istio.enabled }}true{{ else }}false{{ end }}
  {{- if or .Values.monitoring.enabled .Values.istio.enabled }}
  dependsOn:
  {{- if .Values.istio.enabled }}
  - name: istio
    namespace: {{ .Release.Namespace}}
  {{- end}}
  {{- if .Values.monitoring.enabled }}
  - name: monitoring
    namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- end }}
{{- end }}
