{{- if .Values.addons.mattermost.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mattermost
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: mattermost
    app.kubernetes.io/component: "collaboration-tools"
    {{- include "commonLabels" . | nindent 4}}
spec:
  releaseName: mattermost
  targetNamespace: mattermost
  chart:
    spec:
      chart: {{ .Values.addons.mattermost.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: mattermost
        namespace: {{ .Release.Namespace }}

  {{- with .Values.flux }}
  interval: {{ .interval }}
  test:
    enable: false
  install:
    remediation:
      retries: {{ .install.retries }}
  upgrade:
    remediation:
      retries: {{ .upgrade.retries }}
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: {{ .rollback.timeout }}
    cleanupOnFail: {{ .rollback.cleanupOnFail }}
  {{- end }}

  valuesFrom:
    - name: {{ .Release.Name }}-mattermost-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-mattermost-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-mattermost-values
      kind: Secret
      valuesKey: "overlays"

  dependsOn:
    - name: mattermost-operator
      namespace: {{ .Release.Namespace }}

    {{- if .Values.istio.enabled }}
    - name: istio
      namespace: {{ .Release.Namespace }}
    {{- end }}

    {{- with .Values.addons.mattermost.objectStorage }}
    {{- if not (and .endpoint .accessKey .accessSecret .bucket) }}
    - name: minio-operator
      namespace: {{ $.Release.Namespace }}
    {{- end }}
    {{- end }}
{{- end }}
