{{- if and .Values.istio.enabled ( or .Values.addons.authservice.enabled .Values.monitoring.sso.enabled .Values.jaeger.sso.enabled ) }}
apiVersion: v1
kind: Namespace
metadata:
  name: authservice
  {{- if .Values.istio.enabled }}
  labels:
    istio-injection: enabled
  {{- end }}

{{- if ( include "imagePullSecret" . ) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: authservice
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}

{{- end }}