{{- $fluxSettingsClusterAuditor := merge .Values.clusterAuditor.flux .Values.flux -}}
{{- if .Values.clusterAuditor.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster-auditor
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: cluster-auditor
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
spec:
  targetNamespace: logging
  chart:
    spec:
      chart: {{ .Values.clusterAuditor.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: cluster-auditor
        namespace: {{ .Release.Namespace }}

  {{- toYaml $fluxSettingsClusterAuditor | nindent 2 }}

  {{- if .Values.clusterAuditor.postRenderers }}
  postRenderers:
  {{ toYaml .Values.clusterAuditor.postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-cluster-auditor-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-cluster-auditor-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-cluster-auditor-values
      kind: Secret
      valuesKey: "overlays"

  values:
    elasticsearch:
      imagePullSecrets:
      - name: private-registry

  dependsOn:
  - name: ek
    namespace: {{ .Release.Namespace }}
  - name: gatekeeper
    namespace: {{ .Release.Namespace}}
{{- end }}