{{- if .Values.addons.minio.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: minio
  labels:
    istio-injection: enabled
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: "application-utilities"
    {{- include "commonLabels" . | nindent 4}}
---
{{- if (   include "imagePullSecret" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: minio
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
---
# probably want to get rid of this eventually
apiVersion: v1
kind: Secret
metadata:
  name: minio-root-creds-secret
  namespace: minio
type: Opaque
data:
  accesskey: {{ .Values.addons.minio.accesskey | default "minio" | b64enc }}
  secretkey: {{ .Values.addons.minio.secretkey | default "minio123" | b64enc }}
{{- end }}
