{{- if .Values.addons.minio.enabled }}
# probably want to get rid of this eventually
apiVersion: v1
kind: Secret
metadata:
  name: minio-root-creds-secret
  namespace: minio
type: Opaque
data:
  accesskey: {{ .Values.addons.minio.accesskey | default "minio" | b64enc }}
  secretkey: {{ .Values.addons.minio.secretkey | default "minio123" | b64enc }}
{{- end }}