{{- $fluxSettingsEckOperator := merge .Values.eckoperator.flux .Values.flux -}}
{{- if or .Values.eckoperator.enabled .Values.logging.enabled .Values.clusterAuditor.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eck-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: eck-operator
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
spec:
  targetNamespace: eck-operator
  chart:
    spec:
      chart: {{ .Values.eckoperator.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: eck-operator
        namespace: {{ .Release.Namespace }}

  {{- toYaml $fluxSettingsEckOperator | nindent 2 }}

  {{- if .Values.eckoperator.postRenderers }}
  postRenderers:
  {{ toYaml .Values.eckoperator.postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-eck-operator-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-eck-operator-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-eck-operator-values
      kind: Secret
      valuesKey: "overlays"

  {{- if .Values.gatekeeper.enabled }}
  dependsOn:
    - name: gatekeeper
      namespace: {{ .Release.Namespace }}
  {{- end }}
{{- end }}