{{- if or .Values.addons.minioOperator.enabled .Values.addons.minio.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: minio-operator
  labels:
    istio-injection: enabled
    app.kubernetes.io/name: minioOperator
    app.kubernetes.io/component: "application-utilities"
    {{- include "commonLabels" . | nindent 4}}

---
{{- if ( include "imagePullSecret" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: minio-operator
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}