{{- if .Values.addons.anchore.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: {{ .Release.Name }}-anchore
  name: anchore

---
{{- if ( include "imagePullSecret" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: anchore
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}