{{- if and .Values.kiali.enabled .Values.kiali.sso.client_secret }}
apiVersion: v1
kind: Secret
metadata:
  name: kiali-openid
  namespace: kiali
type: kubernetes.io/opaque
stringData:
  oidc-secret: {{ .Values.kiali.sso.client_secret }}
{{- end }}