{{- if or .Values.gatekeeper.enabled .Values.clusterAuditor.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.gatekeeper "name" "gatekeeper" "defaults" (include "bigbang.defaults.gatekeeper" .)) }}
{{- end }}

{{- define "bigbang.defaults.gatekeeper" -}}
disableValidatingWebhook: true
createNamespace: false
image:
  pullSecrets:
  - name: private-registry
{{- end -}}
