{{- if .Values.addons.gitlabRunner.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: {{ .Release.Namespace }}
spec:
  targetNamespace: gitlab
  releaseName: gitlab-runner
  chart:
    spec:
      chart: {{ .Values.addons.gitlabRunner.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: gitlab-runner
        namespace: {{ .Release.Namespace }}

  {{- with .Values.flux }}
  interval: {{ .interval }}
  test:
    enable: false
  install:
    remediation:
      retries: {{ .install.retries }}
  upgrade:
    remediation:
      retries: {{ .upgrade.retries }}
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: {{ .rollback.timeout }}
    cleanupOnFail: {{ .rollback.cleanupOnFail }}
  {{- end }}

  valuesFrom:
    - name: {{ .Release.Name }}-gitlab-runner-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-gitlab-runner-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-gitlab-runner-values
      kind: Secret
      valuesKey: "overlays"

  {{- if or .Values.gatekeeper.enabled .Values.monitoring.enabled .Values.addons.gitlab.enabled }}
  dependsOn:
    {{- if .Values.gatekeeper.enabled }}
    - name: gatekeeper
      namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if .Values.monitoring.enabled }}
    - name: monitoring
      namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if .Values.addons.gitlab.enabled }}
    - name: gitlab
      namespace: {{ .Release.Namespace }}
    {{- end }}
  {{- end }}
{{- end }}