{{- if or .Values.logging.enabled .Values.clusterAuditor.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ek
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: logging
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
spec:
  targetNamespace: logging
  chart:
    spec:
      chart: {{ .Values.logging.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: elasticsearch-kibana
        namespace: {{ .Release.Namespace }}

  {{- with .Values.flux }}
  interval: {{ .interval }}
  test:
    enable: false
  install:
    remediation:
      retries: {{ .install.retries }}
  upgrade:
    remediation:
      retries: {{ .upgrade.retries }}
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: {{ .rollback.timeout }}
    cleanupOnFail: {{ .rollback.cleanupOnFail }}
  {{- end }}

  valuesFrom:
    - name: values
      kind: Secret
      valuesKey: "logging.yaml"

  values:
    hostname: {{ .Values.hostname }}
    istio:
      enabled: {{ .Values.istio.enabled }}
    {{- if .Values.logging.sso.enabled }}
    sso:
      enabled: {{ .Values.logging.sso.enabled }}
      client_id: {{ .Values.logging.sso.client_id }}
      client_secret: {{ .Values.logging.sso.client_secret }}
      oidc:
        host: {{ .Values.sso.oidc.host }}
        realm: {{ .Values.sso.oidc.realm }}
    {{- end }}
    kibana:
      version: 7.9.2
      imagePullSecrets:
      - name: private-registry
    elasticsearch:
      version: 7.9.2
      imagePullSecrets:
      - name: private-registry

  {{/* ECK and Logging _always_ depend on .Values.logging being enabled, so can assume they exist here */}}
  dependsOn:
    - name: eck-operator
      namespace: {{ .Release.Namespace }}

    {{- if  .Values.gatekeeper.enabled }}
    - name: gatekeeper
      namespace: {{ .Release.Namespace }}
    {{- end }}

    {{- if .Values.istio.enabled }}
    - name: istio
      namespace: {{ .Release.Namespace }}
    {{- end }}
{{- end }}