{{- if or .Values.logging.enabled .Values.clusterAuditor.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.logging "name" "ek" "defaults" (include "bigbang.defaults.logging" .)) }}
{{- end }}

{{- define "bigbang.defaults.logging" -}}
hostname: {{ .Values.hostname }}
istio:
  enabled: {{ .Values.istio.enabled }}

{{- if .Values.logging.sso.enabled }}
sso:
  enabled: {{ .Values.logging.sso.enabled }}
  client_id: {{ .Values.logging.sso.client_id }}
  client_secret: {{ .Values.logging.sso.client_secret | default "no-secret" }}
  oidc:
    host: {{ .Values.sso.oidc.host }}
    realm: {{ .Values.sso.oidc.realm }}
{{- end }}

kibana:
  version: 7.9.2
  imagePullSecrets:
    - name: private-registry

elasticsearch:
  version: 7.9.2
  imagePullSecrets:
    - name: private-registry
{{- end -}}
