{{- if .Values.addons.gitlab.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gitlab
    app.kubernetes.io/component: "developer-tools"
    {{- include "commonLabels" . | nindent 4}}
spec:
  releaseName: gitlab
  targetNamespace: gitlab
  chart:
    spec:
      chart: {{ .Values.addons.gitlab.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: gitlab
        namespace: {{ .Release.Namespace }}
  timeout: 10m
{{- with .Values.flux }}
  interval: {{ .interval }}
  test:
    enable: false
  install:
    remediation:
      retries: {{ .install.retries }}
  upgrade:
    remediation:
      retries: {{ .upgrade.retries }}
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: {{ .rollback.timeout }}
    cleanupOnFail: {{ .rollback.cleanupOnFail }}
  {{- end }}

  valuesFrom:
    - name: {{ .Release.Name }}-gitlab-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-gitlab-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-gitlab-values
      kind: Secret
      valuesKey: "overlays"

  {{- if or .Values.gatekeeper.enabled .Values.istio.enabled .Values.monitoring.enabled }}
  dependsOn:
  {{- if .Values.gatekeeper.enabled }}
  - name: gatekeeper
    namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.istio.enabled }}
  - name: istio
    namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.monitoring.enabled }}
  - name: monitoring
    namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- end }}
{{- end }}